---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking
